# Generated by Django 4.2.7 on 2023-11-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_movie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster_path',
            field=models.FileField(blank=True, upload_to='posters/'),
        ),
    ]
